# Generated by Django 5.2.8 on 2025-11-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('prioridade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Concluída', 'Tarefa Concluída'), ('Iniciado', 'Tarefa iniciada'), ('Incompleta', 'Tarefa Incompleta')], default='Incompleta', max_length=10)),
                ('data_limite', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarefas.projeto')),
            ],
        ),
    ]
